export const GET_COUNTRIES = "GET COUNTRIES";
export const FIND_ALL_COUNTRIES_BY_CONTINENT =
  "FIND ALL COUNTRIES BY CONTINENT";
export const FIND_ALL_COUNTRIES_BY_SUBREGION =
  "FIND ALL COUNTRIES BY SUBREGION";
export const FIND_ALL_COUNTRIES_WHIT_POPULATION_GREATER_THAN_OR_EQUAL =
  "FIND ALL COUNTRIES WHIT POPULATION GREATER THAN OR EQUAL";
export const FIND_ALL_COUNTRIES_WHIT_POPULATION_LESS_THAN_OR_EQUAL =
  "FIND ALL COUNTRIES WHIT POPULATION LESS THAN OR EQUAL";
export const FIND_ALL_COUNTRIES_WHIT_POPULATION_BETWEEN =
  "FIND ALL COUNTRIES WHIT POPULATION BETWEEN";
export const FIND_ALL_COUNTRIES_BY_ACTIVITY_NAME =
  "FIND ALL COUNTRIES BY ACTIVITY NAME";
export const FIND_ALL_COUNTRIES_BY_ACTIVITY_ID =
  "FIND ALL COUNTRIES BY ACTIVITY ID";
export const CLEAN_COUNTRIES = "CLEAN COUNTRIES";
export const GET_COUNTRY_DETAIL = "GET COUNTRY DETAIL";
export const GET_ACTIVITIES = "GET ACTIVITIES";
export const ADD_ACTIVITY = "ADD ACTIVITY";
export const GET_ACTIVITIES_BY_SEASON = "GET ACTIVITIES BY SEASON";
export const GET_ACTIVITIES_BY_DIFFICULTY = "GET ACTIVITIES BY DIFFICULTY";
export const GET_ACTIVITY_BY_NAME = "GET ACTIVITY BY NAME";
export const GET_ACTIVITIES_BY_COUNTRY_ID = "GET ACTIVITIES BY COUNTRY ID";
export const GET_ACTIVITIES_BY_COUNTRY_NAME = "GET ACTIVITIES BY COUNTRY NAME";
export const CREATE_ACTIVITY = "CREATE ACTIVITY";
export const UPDATE_ACTIVITY_BY_ID = "UPDATE ACTIVITY BY ID";
export const DELETE_ACTIVITY_BY_ID = "DELETE ACTIVITY BY ID";